#-version: 2.0.0--accepts-"" ok--'' ok
#https://docs.getdbt.com/reference/commands/seed
#-   PROJECT_DEV  pjt_may2ndhalf
name :  "PROJECT_DEV"
model-paths: ['mmodels']
seed-paths: ['seeds']
analysis-paths: ['analysis']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
test-paths: ['tests']


target-path: "target"
clean-targets: 
  - 'targets'
  - 'dbt-packages'
#clean-targets: [target, dbt_packages, logs]

require-dbt-version: ">=1.0.0"
config-version: 2


vars:
  'dbt_date:time_zone': 'America/Los_Angeles'
  # The `start_date` variable will be accessible in all resources
  start_date: '2016-06-01'

  # The `platforms` variable is only accessible to resources in the my_dbt_project project
  my_dbt_project:
    platforms: ['web', 'mobile']

  # The `app_ids` variable is only accessible to resources in the snowplow package
  snowplow:
    app_ids: ['marketing', 'app', 'landing-page']

tests:
  project_dev:
    +severity: warn
# project level if any severity then it will warns us during job excution..

    
